export const shopCategories = [
    { value: "pet", label: "Pet Supplies and Services" },
    { value: "music", label: "Music Instruments and Stores" },
    { value: "grocery", label: "Grocery and Supermarket" },
    { value: "fashion", label: "Fashion and Apparel" },
    { value: "electronics", label: "Electronics and Gadgets" },
    { value: "beauty", label: "Beauty and Personal Care" },
    { value: "pharmacy", label: "Pharmacy and Medical Store" },
    { value: "bakery", label: "Bakery and Confectionery" },
    { value: "restaurant", label: "Restaurant and Cafe" },
    { value: "hardware", label: "Hardware and Tools" },
    { value: "furniture", label: "Furniture and Home Decor" },
    { value: "books", label: "Books and Stationery" },
    { value: "sports", label: "Sports and Fitness Equipment" },
    { value: "florist", label: "Florist and Garden Supplies" },
    { value: "jewelry", label: "Jewelry and Accessories" },
    { value: "toys", label: "Toys and Games" },
    { value: "automotive", label: "Automotive Parts and Services" },
    { value: "mobile", label: "Mobile Phones and Accessories" },
    { value: "computer", label: "Computers and IT Services" },
    { value: "optical", label: "Optical and Eyewear" },
    { value: "travel", label: "Travel and Tour Services" },
    { value: "laundry", label: "Laundry and Dry Cleaning" },
    { value: "education", label: "Education and Training Services" },
    { value: "art", label: "Art and Craft Supplies" },
    { value: "baby", label: "Baby Products and Maternity Care" },
    { value: "gaming", label: "Gaming and Consoles" },
    { value: "real_estate", label: "Real Estate Services" },
    { value: "salon", label: "Salon and Spa Services" },
    { value: "event", label: "Event Management Services" },
    { value: "printing", label: "Printing and Advertising Services" },
  ];